using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SecondDesktopHotkeyManagerDll
{
    public enum LKey : int
    {
        None	= 0,
        Ctrl	= (int)Keys.Control,
		Shift	= (int)Keys.Shift,
		Alt		= (int)Keys.Alt,
    }

    public enum RKey : int
    {
        None		= 0,
        Space		= (int)Keys.Space,
        PageUp		= (int)Keys.PageUp,
        PageDown	= (int)Keys.PageDown,
        End			= (int)Keys.End,
        Home		= (int)Keys.Home,
        Left		= (int)Keys.Left,
        Up			= (int)Keys.Up,
        Right		= (int)Keys.Right,
        Down		= (int)Keys.Down,
        Insert		= (int)Keys.Insert,
        Delete		= (int)Keys.Delete,
        D0			= (int)Keys.D0,
        D1			= (int)Keys.D1,
        D2			= (int)Keys.D2,
        D3			= (int)Keys.D3,
        D4			= (int)Keys.D4,
        D5			= (int)Keys.D5,
        D6			= (int)Keys.D6,
        D7			= (int)Keys.D7,
        D8			= (int)Keys.D8,
        D9			= (int)Keys.D9,
        A			= (int)Keys.A,
        B			= (int)Keys.B,
        C			= (int)Keys.C,
        D			= (int)Keys.D,
        E			= (int)Keys.E,
        F			= (int)Keys.F,
        G			= (int)Keys.G,
        H			= (int)Keys.H,
        I			= (int)Keys.I,
        J			= (int)Keys.J,
        K			= (int)Keys.K,
        L			= (int)Keys.L,
        M			= (int)Keys.M,
        N			= (int)Keys.N,
        O			= (int)Keys.O,
        P			= (int)Keys.P,
        Q			= (int)Keys.Q,
        R			= (int)Keys.R,
        S			= (int)Keys.S,
        T			= (int)Keys.T,
        U			= (int)Keys.U,
        V			= (int)Keys.V,
        W			= (int)Keys.W,
        X			= (int)Keys.X,
        Y			= (int)Keys.Y,
        Z			= (int)Keys.Z,
        NumPad0		= (int)Keys.NumPad0,
        NumPad1		= (int)Keys.NumPad1,
        NumPad2		= (int)Keys.NumPad2,
        NumPad3		= (int)Keys.NumPad3,
        NumPad4		= (int)Keys.NumPad4,
        NumPad5		= (int)Keys.NumPad5,
        NumPad6		= (int)Keys.NumPad6,
        NumPad7		= (int)Keys.NumPad7,
        NumPad8		= (int)Keys.NumPad8,
        NumPad9		= (int)Keys.NumPad9,
        F1			= (int)Keys.F1,
        F2			= (int)Keys.F2,
        F3			= (int)Keys.F3,
        F4			= (int)Keys.F4,
        F5			= (int)Keys.F5,
        F6			= (int)Keys.F6,
        F7			= (int)Keys.F7,
        F8			= (int)Keys.F8,
        F9			= (int)Keys.F9,
        F10			= (int)Keys.F10,
        F11			= (int)Keys.F11,
        F12			= (int)Keys.F12,
        F13			= (int)Keys.F13,
        F14			= (int)Keys.F14,
        F15			= (int)Keys.F15,
        F16			= (int)Keys.F16,
        F17			= (int)Keys.F17,
        F18			= (int)Keys.F18,
        F19			= (int)Keys.F19,
        F20			= (int)Keys.F20,
        F21			= (int)Keys.F21,
        F22			= (int)Keys.F22,
        F23			= (int)Keys.F23,
        F24			= (int)Keys.F24,
        NumLock		= (int)Keys.NumLock,
    }
}
